apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: lang
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50M
  hostPath:
    path: /run/desktop/mnt/host/c/Users/alvar/data/db
