apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: lang
  name: mongo-data-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: mongo-data
  resources:
    requests:
      storage: 50M
